<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>25b144d8-793d-4894-b966-e17508082684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/aside/div[2]/div[2]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>379c129f-6a90-4167-add2-57aefe2c5513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>2f831e6c-15a5-47f4-84c2-ccf3f61456ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background&quot;]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-[280px_1fr] min-h-[calc(100vh-73px)] lg:min-h-screen&quot;]/aside[@class=&quot;fixed lg:sticky top-0 left-0 z-40 w-[200px] lg:w-[280px] h-screen bg-gray-100 border-r border-gray-200 
          flex flex-col transition-transform duration-300 ease-in-out
          -translate-x-full lg:translate-x-0&quot;]/div[@class=&quot;p-md pt-0 pb-1 space-y-0 flex-shrink-0&quot;]/div[@class=&quot;border-t border-gray-200 pt-sm&quot;]/div[@class=&quot;pt-2&quot;]/button[@class=&quot;gap-2 whitespace-nowrap text-sm font-medium ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 h-10 px-4 py-2 flex items-center space-x-3 px-md py-sm rounded-md transition-colors duration-150 w-full justify-start text-red-600 hover:bg-red-100 hover:text-red-700&quot;]/span[1]</value>
      <webElementGuid>bc2fa747-a7ec-4455-a8ef-be39945c4342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/aside/div[2]/div[2]/div/button/span</value>
      <webElementGuid>361d6b9b-f096-4f54-8797-4a80cf136800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s@gmail.com'])[1]/following::span[1]</value>
      <webElementGuid>5e72c38b-c99e-4613-8917-24a5c8dfddb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[2]</value>
      <webElementGuid>821d57e6-5488-4383-96a3-07d7f5e181e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitor and Analyze Performance'])[1]/preceding::span[1]</value>
      <webElementGuid>e03e1d70-2c10-49cf-b962-4b104c8691a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share Feedback'])[1]/preceding::span[1]</value>
      <webElementGuid>5d376bf3-6144-4cb2-86bc-46b9a1542c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>5e2d9f73-616f-4baf-9b47-a2095ef34b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>6cfe58bd-097b-403d-8db0-0918d2e4ae1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>fa5498de-a4e5-4400-ad62-53e20115814a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
